-- Provisiona la gestión de slides sin exponer escrituras públicas.
-- Este script es idempotente: conserva los slides existentes y solo carga
-- los tres iniciales cuando la tabla está vacía.

CREATE TABLE IF NOT EXISTS public.slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    orden INT NOT NULL DEFAULT 0,
    title TEXT NOT NULL,
    subtitle TEXT,
    image_url TEXT,
    button_text TEXT,
    button_link TEXT
);

ALTER TABLE public.slides ENABLE ROW LEVEL SECURITY;

-- La portada puede leer los slides sin iniciar sesión.
DROP POLICY IF EXISTS "Permitir lectura pública de slides" ON public.slides;
CREATE POLICY "Permitir lectura pública de slides"
ON public.slides
FOR SELECT
TO anon, authenticated
USING (true);

-- El administrador ya exige una sesión de Supabase; solo esa sesión escribe.
DROP POLICY IF EXISTS "Permitir gestión total de slides" ON public.slides;
DROP POLICY IF EXISTS "Admins authenticated full access slides" ON public.slides;
CREATE POLICY "Admins authenticated full access slides"
ON public.slides
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

REVOKE ALL ON TABLE public.slides FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.slides TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON TABLE public.slides TO authenticated;
REVOKE ALL ON SEQUENCE public.slides_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.slides_id_seq TO authenticated;

INSERT INTO public.slides (orden, title, subtitle, image_url, button_text, button_link)
SELECT seed.orden, seed.title, seed.subtitle, seed.image_url, seed.button_text, seed.button_link
FROM (
    VALUES
        (1, 'Soluciones Agrícolas de Alto Rendimiento', 'Impulsando la productividad del campo ecuatoriano.', 'IMAGENES/slide1.webp', 'Ver Portafolio', '#productos'),
        (2, 'Fertilidad y Productividad', 'Fórmulas de alta eficiencia para nutrición vegetal.', 'IMAGENES/slide2.webp', 'VER PRODUCTOS', 'productos.html'),
        (3, 'Línea Master Protec', 'Menos volatilización, más absorción, mejores cosechas.', 'IMAGENES/slide3.webp', 'Conocer más', '#')
) AS seed(orden, title, subtitle, image_url, button_text, button_link)
WHERE NOT EXISTS (SELECT 1 FROM public.slides);
