-- Ejecuta este script en el SQL Editor de Supabase para activar la gestión de Slices.

-- 1. Crear la tabla de slides
CREATE TABLE IF NOT EXISTS slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    orden INT DEFAULT 0,
    title TEXT NOT NULL,
    subtitle TEXT,
    image_url TEXT,
    button_text TEXT,
    button_link TEXT
);

-- 2. Habilitar RLS (Seguridad de Nivel de Fila)
ALTER TABLE slides ENABLE ROW LEVEL SECURITY;

-- 3. Crear política para permitir lectura pública
CREATE POLICY "Permitir lectura pública de slides" 
ON slides FOR SELECT 
USING (true);

-- 4. Crear política para permitir gestión total (esto es temporal o para entorno admin)
-- Nota: En un entorno de producción real, se debería restringir por rol o auth.uid().
CREATE POLICY "Permitir gestión total de slides" 
ON slides FOR ALL 
USING (true) 
WITH CHECK (true);

-- 5. Insertar los slides actuales como base (Opcional, pero recomendado para el primer despliegue)
INSERT INTO slides (orden, title, subtitle, image_url, button_text, button_link)
VALUES 
(1, 'Soluciones Agrícolas de Alto Rendimiento', 'Impulsando la productividad del campo ecuatoriano.', 'IMAGENES/slide1.jpg', 'Ver Portafolio', '#productos'),
(2, 'Fertilidad y Productividad', 'Fórmulas de alta eficiencia para nutrición vegetal.', 'IMAGENES/slide2.jpg', 'VER PRODUCTOS', 'productos.html'),
(3, 'Línea Master Protec', 'Protección orgánica para una agricultura sostenible.', 'IMAGENES/slide3.jpg', 'Conocer más', '#');
